"""Generate a Notion-friendly daily_summary.json file.

This script writes `data/daily_summary.json` following a canonical schema
that aligns with Notion properties (date, title, rich text, toggles, metrics,
links). It can be extended later, but always preserves the base shape expected
by the frontend and downstream automations.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).parent
OUTPUT_PATH = ROOT / "data" / "daily_summary.json"


def build_default_payload(now: datetime | None = None) -> Dict[str, Any]:
    """Return a default daily summary payload using the canonical schema."""

    now = now or datetime.now(timezone.utc)
    date_str = now.date().isoformat()
    generated_at = now.isoformat().replace("+00:00", "Z")

    return {
        "meta": {
            "run_id": date_str,
            "generated_at_utc": generated_at,
            "version": "v1",
        },
        "summary": {
            "date": date_str,
            "title": f"Daily Briefing – {date_str}",
            "overview": "Short 2–4 sentence overview of the day’s key themes.",
            "categories": ["Personal", "Finance", "Real Assets"],
        },
        "sections": [
            {
                "name": "Top Priorities",
                "items": [
                    "Finalize Trenton Hotel investor update deck.",
                    "Review La Sandwicherie SBA model v3.",
                    "Block 2 hours for MSF prep (TVM & duration).",
                ],
            },
            {
                "name": "Markets & Macro",
                "items": [
                    "10Y UST yield moved from 4.20% to 4.35%.",
                    "Equities up ~0.5% led by tech.",
                    "BTC consolidating near $X.",
                ],
            },
            {
                "name": "Deals & Projects",
                "items": [
                    "Email follow-up sent to Newark capital partner.",
                    "Scheduled call with La Sandwicherie lender for Friday.",
                ],
            },
        ],
        "metrics": {
            "focus_hours": 4.5,
            "tasks_completed": 7,
            "sleep_hours": 6.0,
        },
        "links": [
            {
                "label": "Daily summary docx",
                "url": "https://github.com/your/repo/raw/main/outputs/daily_summary.docx",
            },
            {
                "label": "GitHub run",
                "url": "https://github.com/your/repo/actions/runs/123456789",
            },
        ],
    }


def write_daily_summary(payload: Dict[str, Any] | None = None) -> None:
    """Write the canonical daily summary JSON to disk.

    Args:
        payload: Optional payload to write. If omitted, the default payload
            generated by :func:`build_default_payload` is used.
    """

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    data = payload or build_default_payload()

    with OUTPUT_PATH.open("w", encoding="utf-8") as fp:
        json.dump(data, fp, ensure_ascii=False, indent=2)
        fp.write("\n")


if __name__ == "__main__":
    write_daily_summary()
